services:
    postgres:
        image: postgres:18
        container_name: task_manager_project
        restart: always
        environment:
            POSTGRES_USER: admin
            POSTGRES_PASSWORD: taskmanager123
            POSTGRES_DB: task_manager
        ports:
            - '5432:5432'
        volumes:
            - postgres_data:/var/lib/postgresql

volumes:
    postgres_data:
        driver: local
